---
- name: Deactive the VNF licenses
  hosts: localhost
  gather_facts: False
  vars_files:
    - ../variables.yml
  tasks:
    - name: Deactive Licenses
      panos_de_lic:
        ip_address: "{{ panos_s.ip_address }}"
        username: "{{ lic.username }}"
        password: "{{ lic.password }}"
        auto: True
        api_key: "{{ lic.api_key }}"
    - pause:
        seconds: 10
